version: '3.9'
services:
  api:
    build: 
      context: ./api
    ports:
      - ${HOST_PORT}:${NODE_PORT}
    volumes:
      - ./api:/app
      - /app/node_modules
  
  front:
    build: 
      context: ./front
    ports:
      - ${REACT_HOST_PORT}:${REACT_PORT}
    volumes:
      - ./front:/app
      - /app/node_modules
  
  mongodb:
    image: mongo:6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sanjeev
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis:7.0.10

volumes:
   mongo-db: